export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    testimonials: 10,
    widgets: 1,
    requestEmails: 0,
    aiFeatures: false,
    removeBranding: false,
    importSources: ["direct"],
  },
  pro: {
    name: "Pro",
    price: 12,
    testimonials: Infinity,
    widgets: Infinity,
    requestEmails: 50,
    aiFeatures: true,
    removeBranding: true,
    importSources: ["direct", "google", "trustpilot", "yelp", "facebook", "g2"],
  },
  business: {
    name: "Business",
    price: 25,
    testimonials: Infinity,
    widgets: Infinity,
    requestEmails: Infinity,
    aiFeatures: true,
    removeBranding: true,
    importSources: ["direct", "google", "trustpilot", "yelp", "facebook", "g2", "twitter"],
    teamSeats: true,
    customDomain: true,
    apiAccess: true,
    whiteLabel: true,
  },
} as const;

export const PLATFORMS = [
  { id: "google", name: "Google", color: "#4285F4", emoji: "🔵" },
  { id: "trustpilot", name: "Trustpilot", color: "#00B67A", emoji: "🟢" },
  { id: "facebook", name: "Facebook", color: "#1877F2", emoji: "🔷" },
  { id: "g2", name: "G2", color: "#FF492C", emoji: "🟡" },
  { id: "yelp", name: "Yelp", color: "#D32323", emoji: "🔴" },
  { id: "twitter", name: "Twitter/X", color: "#000000", emoji: "🐦" },
] as const;

export const WIDGET_TYPES = [
  { id: "wall", name: "Wall", description: "Masonry grid of all testimonials" },
  { id: "carousel", name: "Carousel", description: "Rotating slider" },
  { id: "card", name: "Card", description: "Single featured testimonial" },
  { id: "marquee", name: "Marquee", description: "Scrolling ticker" },
  { id: "badge", name: "Badge", description: "Compact rating badge" },
  { id: "grid", name: "Grid", description: "Fixed 3-column grid" },
  { id: "popup", name: "Popup", description: "Corner notification popup" },
  { id: "list", name: "List", description: "Simple vertical list" },
] as const;

export const BUSINESS_TYPES = [
  "SaaS / Software",
  "Freelancer",
  "Agency",
  "E-commerce",
  "Local Business",
  "Consulting",
  "Education",
  "Other",
] as const;

export const NAV_ITEMS = [
  { href: "/dashboard", label: "Overview", icon: "LayoutDashboard" },
  { href: "/dashboard/demo/testimonials", label: "Testimonials", icon: "MessageSquare" },
  { href: "/dashboard/demo/reviews", label: "Reviews", icon: "Star" },
  { href: "/dashboard/demo/widgets", label: "Widgets", icon: "Layout" },
  { href: "/dashboard/demo/requests", label: "Requests", icon: "Send" },
  { href: "/dashboard/demo/analytics", label: "Analytics", icon: "BarChart2" },
  { href: "/dashboard/demo/settings", label: "Settings", icon: "Settings" },
] as const;

export const SEED_TESTIMONIALS = [
  {
    id: "1",
    name: "Sarah Johnson",
    title: "CEO",
    company: "TechCorp",
    rating: 5,
    text: "Working with this team was an absolute game-changer for our business. The results exceeded all expectations and the process was seamless from start to finish.",
    tags: ["quality", "results", "communication"],
    status: "approved",
    source: "direct",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
  },
  {
    id: "2",
    name: "Mike Torres",
    title: "Founder",
    company: "GrowthLabs",
    rating: 5,
    text: "I've tried every social proof tool on the market. TrustFlow is the only one that actually converts. Our signup rate went up 34% in the first month.",
    tags: ["results", "speed"],
    status: "approved",
    source: "google",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
  },
  {
    id: "3",
    name: "Anna Li",
    title: "Marketing Director",
    company: "Bloom Agency",
    rating: 5,
    text: "The widget builder is incredible. We had beautiful testimonials on our site within 10 minutes. Our clients love seeing real reviews front and centre.",
    tags: ["ease-of-use", "design"],
    status: "pending",
    source: "direct",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    id: "4",
    name: "Chris Patel",
    title: "Product Manager",
    company: "Launchpad SaaS",
    rating: 4,
    text: "The AI polish feature is genuinely impressive. It took my customers' rough feedback and turned it into compelling testimonials without changing the meaning.",
    tags: ["AI", "quality"],
    status: "approved",
    source: "trustpilot",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    id: "5",
    name: "Emma Wilson",
    title: "Owner",
    company: "Willow & Co.",
    rating: 5,
    text: "As a small business owner I was sceptical, but TrustFlow paid for itself in the first week. Customer trust is everything and this tool delivers it.",
    tags: ["value", "results"],
    status: "pending",
    source: "direct",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    id: "6",
    name: "James Okafor",
    title: "CTO",
    company: "BuildFast",
    rating: 5,
    text: "Integrating TrustFlow took less than 5 minutes. The embed code just works, the widget looks gorgeous, and the analytics are actually useful.",
    tags: ["developer", "ease-of-use"],
    status: "approved",
    source: "google",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
  {
    id: "7",
    name: "Rachel Kim",
    title: "Head of Sales",
    company: "Velocity CRM",
    rating: 5,
    text: "We use TrustFlow on every landing page and proposal deck. Prospects see real customer stories and it shortens our sales cycle noticeably.",
    tags: ["sales", "results"],
    status: "rejected",
    source: "direct",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
  },
] as const;
